### ISSUE TITLE
Undefined offsets in PingParserForWindows

### ISSUE THREAD

**Issue by sts-ryan-holton** [angelcamposm/ping#14]
On a Windows machine, using the latest version of this package in a Laravel 8 installation, with PHP 7.4, I'm trying to use the Ping library via my controller but get several different undefined offset errors.

### ping: https://amazon.co.uk/

```php
$command = (new PingCommandBuilder('https://amazon.co.uk/'));
$ping = (new Ping($command))->run();
```

```
ErrorException: Undefined offset: 1 in file C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Parsers\PingParserForWindows.php on line 116

#0 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Parsers\PingParserForWindows.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Parsers\PingParserForWindows.php(166): Acamposm\Ping\Parsers\PingParserForWindows->parseRoundTripTime()
#2 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Parsers\PingParserForWindows.php(25): Acamposm\Ping\Parsers\PingParserForWindows->setRoundTripTime()
#3 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Ping.php(59): Acamposm\Ping\Parsers\PingParserForWindows->__construct()
#4 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Ping.php(79): Acamposm\Ping\Ping->parse()
```

### ping: https://google.co.uk

```php
$command = (new PingCommandBuilder('https://google.co.uk'));
$ping = (new Ping($command))->run();
```

```
ErrorException: Undefined offset: 1 in file C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Parsers\PingParserForWindows.php on line 137

#0 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Parsers\PingParserForWindows.php(137): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Parsers\PingParserForWindows.php(184): Acamposm\Ping\Parsers\PingParserForWindows->parseStatistics()
#2 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Parsers\PingParserForWindows.php(27): Acamposm\Ping\Parsers\PingParserForWindows->setStatistics()
#3 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Ping.php(59): Acamposm\Ping\Parsers\PingParserForWindows->__construct()
#4 C:\Users\Ryan\Desktop\web-projects\domain-monitor\domain-monitor-api\vendor\acamposm\ping\src\Ping.php(79): Acamposm\Ping\Ping->parse()
```

**Comment by angelcamposm** [comment]
Hi, I've tried on a fresh Laravel project in Windows 10 these are the results...

Google.co.uk works well for me,

```php
array:13 [
  0 => ""
  1 => "Haciendo ping a google.co.uk [142.250.184.163] con 64 bytes de datos:"
  2 => "Respuesta desde 142.250.184.163: bytes=64 tiempo=26ms TTL=118"
  3 => "Respuesta desde 142.250.184.163: bytes=64 tiempo=26ms TTL=118"
  4 => "Respuesta desde 142.250.184.163: bytes=64 tiempo=26ms TTL=118"
  5 => "Respuesta desde 142.250.184.163: bytes=64 tiempo=26ms TTL=118"
  6 => "Respuesta desde 142.250.184.163: bytes=64 tiempo=26ms TTL=118"
  7 => ""
  8 => b"Estad¡sticas de ping para 142.250.184.163:"
  9 => "    Paquetes: enviados = 5, recibidos = 5, perdidos = 0"
  10 => "    (0% perdidos),"
  11 => "Tiempos aproximados de ida y vuelta en milisegundos:"
  12 => b"    M¡nimo = 26ms, M ximo = 26ms, Media = 26ms"
]
```

Amazon.co.uk/ don't work, but amazon.co.uk without ending slash works well...

```php
array:13 [
  0 => ""
  1 => "Haciendo ping a amazon.co.uk [54.239.33.58] con 64 bytes de datos:"
  2 => "Respuesta desde 54.239.33.58: bytes=64 tiempo=53ms TTL=236"
  3 => "Respuesta desde 54.239.33.58: bytes=64 tiempo=52ms TTL=236"
  4 => "Respuesta desde 54.239.33.58: bytes=64 tiempo=52ms TTL=236"
  5 => "Respuesta desde 54.239.33.58: bytes=64 tiempo=52ms TTL=236"
  6 => "Respuesta desde 54.239.33.58: bytes=64 tiempo=52ms TTL=236"
  7 => ""
  8 => b"Estad¡sticas de ping para 54.239.33.58:"
  9 => "    Paquetes: enviados = 5, recibidos = 5, perdidos = 0"
  10 => "    (0% perdidos),"
  11 => "Tiempos aproximados de ida y vuelta en milisegundos:"
  12 => b"    M¡nimo = 52ms, M ximo = 53ms, Media = 52ms"
]
```

So i must clean ending slashes.
